# Generated by Django 2.1 on 2019-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satelite2',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('genbank_id', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('indice', models.CharField(max_length=225)),
                ('satlength', models.IntegerField(blank=True, null=True)),
                ('numrep', models.IntegerField(blank=True, null=True)),
                ('replength', models.IntegerField(blank=True, null=True)),
                ('seed', models.CharField(max_length=225)),
                ('seq', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'satellite',
                'managed': True,
            },
        ),
    ]
